controller:
  joint_state:
    type: joint_state_controller/JointStateController
    publish_rate: 200
  hand_state:
    type: joint_state_controller/JointStateController
    publish_rate: 200
  trajectory:
    type: position_controllers/JointTrajectoryController # Position interface because we are directly passing on commands
    allow_partial_joints_goal: true
    publish_rate: 200
    joints:
      - thumb_brake # FFB
      - index_brake # FFB
      - middle_brake # FFB
      - ring_brake # FFB
      - pinky_brake # FFB
      - thumb_cmc # Buzzer
      - index_mcp # Buzzer
      - middle_mcp # Buzzer
      - ring_mcp # Buzzer
      - pinky_mcp # Buzzer
