fino:
  controller:
    glove_state:
      type: joint_state_controller/JointStateController
      publish_rate: 250
    hand_state:
      type: joint_state_controller/JointStateController
      publish_rate: 250
    trajectory:
      type: position_controllers/JointTrajectoryController
      allow_partial_joints_goal: true
      joints:
        - thumbBrake
        - indexBrake
        - middleBrake
        - ringBrake
        - pinkyBrake